import type { Recipe } from '../types'

export const DEFAULT_RECIPES: Recipe[] = [
  {
    id: 'tacos',
    name: 'Tacos',
    ingredients: [
      { name: 'Tacoskal', amount: '1 förpackning', category: 'torrvaror' },
      { name: 'Köttfärs', amount: '500 g', category: 'kott' },
      { name: 'Tacokrydda', amount: '1 påse', category: 'kryddor' },
      { name: 'Sallad', amount: '1/2 huvud', category: 'gronsaker' },
      { name: 'Tomat', amount: '2 st', category: 'gronsaker' },
      { name: 'Creme fraiche', amount: '1 dl', category: 'mejeri' },
      { name: 'Salsa', amount: '1 burk', category: 'konserver' },
    ],
  },
  {
    id: 'spagetti_bolognese',
    name: 'Spagetti Bolognese',
    ingredients: [
      { name: 'Spagetti', amount: '400 g', category: 'torrvaror' },
      { name: 'Köttfärs', amount: '500 g', category: 'kott' },
      { name: 'Krossade tomater', amount: '2 burkar', category: 'konserver' },
      { name: 'Gul lök', amount: '1 st', category: 'gronsaker' },
      { name: 'Vitlök', amount: '3 klyftor', category: 'gronsaker' },
      { name: 'Olivolja', amount: '2 msk', category: 'kryddor' },
      { name: 'Parmesan', amount: '50 g', category: 'mejeri' },
    ],
  },
  {
    id: 'kycklinggryta',
    name: 'Kycklinggryta',
    ingredients: [
      { name: 'Kycklingfile', amount: '600 g', category: 'kott' },
      { name: 'Kokosmjölk', amount: '1 burk', category: 'konserver' },
      { name: 'Paprika', amount: '2 st', category: 'gronsaker' },
      { name: 'Gul lök', amount: '1 st', category: 'gronsaker' },
      { name: 'Currykrydda', amount: '2 tsk', category: 'kryddor' },
      { name: 'Ris', amount: '3 dl', category: 'torrvaror' },
    ],
  },
  {
    id: 'pannkakor',
    name: 'Pannkakor',
    ingredients: [
      { name: 'Mjöl', amount: '3 dl', category: 'torrvaror' },
      { name: 'Mjölk', amount: '6 dl', category: 'mejeri' },
      { name: 'Ägg', amount: '3 st', category: 'mejeri' },
      { name: 'Smör', amount: '50 g', category: 'mejeri' },
      { name: 'Salt', amount: '1 krm', category: 'kryddor' },
    ],
  },
  {
    id: 'laxpasta',
    name: 'Laxpasta',
    ingredients: [
      { name: 'Pasta', amount: '400 g', category: 'torrvaror' },
      { name: 'Lax', amount: '400 g', category: 'kott' },
      { name: 'Grädde', amount: '2 dl', category: 'mejeri' },
      { name: 'Spenat', amount: '100 g', category: 'gronsaker' },
      { name: 'Citron', amount: '1 st', category: 'gronsaker' },
      { name: 'Dill', amount: '1 kruka', category: 'gronsaker' },
    ],
  },
  {
    id: 'soppa',
    name: 'Grönsakssoppa',
    ingredients: [
      { name: 'Morot', amount: '3 st', category: 'gronsaker' },
      { name: 'Palsternacka', amount: '2 st', category: 'gronsaker' },
      { name: 'Potatis', amount: '4 st', category: 'gronsaker' },
      { name: 'Gul lök', amount: '1 st', category: 'gronsaker' },
      { name: 'Grönsaksbuljongtärning', amount: '2 st', category: 'kryddor' },
      { name: 'Grädde', amount: '1 dl', category: 'mejeri' },
    ],
  },
  {
    id: 'pizza',
    name: 'Hemmagjord pizza',
    ingredients: [
      { name: 'Pizzadeg (färdig)', amount: '1 förpackning', category: 'brod' },
      { name: 'Tomatsås', amount: '1 burk', category: 'konserver' },
      { name: 'Mozzarella', amount: '200 g', category: 'mejeri' },
      { name: 'Skinka', amount: '100 g', category: 'kott' },
      { name: 'Champinjoner', amount: '150 g', category: 'gronsaker' },
    ],
  },
  {
    id: 'kottbullar',
    name: 'Köttbullar med potatismos',
    ingredients: [
      { name: 'Köttbullar', amount: '500 g', category: 'frys' },
      { name: 'Potatis', amount: '1 kg', category: 'gronsaker' },
      { name: 'Mjölk', amount: '1 dl', category: 'mejeri' },
      { name: 'Smör', amount: '50 g', category: 'mejeri' },
      { name: 'Gräddsås', amount: '1 förpackning', category: 'konserver' },
      { name: 'Lingonsylt', amount: '1 burk', category: 'konserver' },
      { name: 'Gurka', amount: '1 st', category: 'gronsaker' },
    ],
  },
  {
    id: 'chili',
    name: 'Chili con carne',
    ingredients: [
      { name: 'Köttfärs', amount: '500 g', category: 'kott' },
      { name: 'Kidneybönor', amount: '2 burkar', category: 'konserver' },
      { name: 'Krossade tomater', amount: '1 burk', category: 'konserver' },
      { name: 'Gul lök', amount: '1 st', category: 'gronsaker' },
      { name: 'Paprika', amount: '1 st', category: 'gronsaker' },
      { name: 'Chilikrydda', amount: '2 tsk', category: 'kryddor' },
      { name: 'Ris', amount: '3 dl', category: 'torrvaror' },
      { name: 'Creme fraiche', amount: '1 dl', category: 'mejeri' },
    ],
  },
  {
    id: 'linsoppa',
    name: 'Linssoppa',
    ingredients: [
      { name: 'Röda linser', amount: '3 dl', category: 'torrvaror' },
      { name: 'Krossade tomater', amount: '1 burk', category: 'konserver' },
      { name: 'Kokosmjölk', amount: '1 burk', category: 'konserver' },
      { name: 'Gul lök', amount: '1 st', category: 'gronsaker' },
      { name: 'Vitlök', amount: '2 klyftor', category: 'gronsaker' },
      { name: 'Ingefära', amount: '1 tsk', category: 'kryddor' },
      { name: 'Currypasta', amount: '1 msk', category: 'kryddor' },
      { name: 'Bröd', amount: '1 limpa', category: 'brod' },
    ],
  },
  {
    id: 'kycklingwok',
    name: 'Kycklingwok',
    ingredients: [
      { name: 'Kycklingfile', amount: '500 g', category: 'kott' },
      { name: 'Wokgrönsaker', amount: '400 g', category: 'gronsaker' },
      { name: 'Nudlar', amount: '300 g', category: 'torrvaror' },
      { name: 'Soja', amount: '3 msk', category: 'kryddor' },
      { name: 'Sesamolja', amount: '1 msk', category: 'kryddor' },
      { name: 'Vitlök', amount: '2 klyftor', category: 'gronsaker' },
      { name: 'Ingefära', amount: '1 tsk', category: 'kryddor' },
    ],
  },
  {
    id: 'fiskgratang',
    name: 'Fiskgratäng',
    ingredients: [
      { name: 'Torskfilé', amount: '600 g', category: 'kott' },
      { name: 'Potatis', amount: '800 g', category: 'gronsaker' },
      { name: 'Grädde', amount: '2 dl', category: 'mejeri' },
      { name: 'Riven ost', amount: '100 g', category: 'mejeri' },
      { name: 'Citron', amount: '1 st', category: 'gronsaker' },
      { name: 'Dill', amount: '1 kruka', category: 'gronsaker' },
    ],
  },
  {
    id: 'pastasallad',
    name: 'Pastasallad med kyckling',
    ingredients: [
      { name: 'Pasta', amount: '300 g', category: 'torrvaror' },
      { name: 'Kycklingfile', amount: '400 g', category: 'kott' },
      { name: 'Körsbärstomater', amount: '200 g', category: 'gronsaker' },
      { name: 'Rucola', amount: '1 påse', category: 'gronsaker' },
      { name: 'Parmesan', amount: '50 g', category: 'mejeri' },
      { name: 'Pesto', amount: '2 msk', category: 'kryddor' },
      { name: 'Olivolja', amount: '2 msk', category: 'kryddor' },
    ],
  },
  {
    id: 'raggmunk',
    name: 'Raggmunk med fläsk',
    ingredients: [
      { name: 'Potatis', amount: '1 kg', category: 'gronsaker' },
      { name: 'Mjöl', amount: '2 dl', category: 'torrvaror' },
      { name: 'Mjölk', amount: '2 dl', category: 'mejeri' },
      { name: 'Ägg', amount: '2 st', category: 'mejeri' },
      { name: 'Fläskskivor', amount: '400 g', category: 'kott' },
      { name: 'Lingonsylt', amount: '1 burk', category: 'konserver' },
      { name: 'Smör', amount: '50 g', category: 'mejeri' },
    ],
  },
]
